import { parseTarget } from '../detector/scanner.js';

const TIMEOUT=5000, MAX_BYTES=340_000, BUNDLE_SLICE=260_000, BUNDLE_BUDGET=6_500_000, MAP_BYTES=900_000, MAX_MAPS=6, MAX_CONFIG_ENDPOINTS=14;

function decodeEscapes(text=''){
  return String(text).replace(/\\u002[fF]/g,'/').replace(/\\u003[aA]/g,':').replace(/\\u0026/g,'&').replace(/\\x2[fF]/g,'/').replace(/\\\//g,'/').replace(/\\"/g,'"').replace(/\\'/g,"'");
}
function foldLiteralConcats(text){let out=text;for(let i=0;i<6;i++){const next=out.replace(/(["'`])([^"'`\n]{0,240})\1\s*\+\s*(["'`])([^"'`\n]{0,240})\3/g,(_,q,a,_q2,b)=>`${q}${a}${b}${q}`);if(next===out)break;out=next;}return out;}
function stringConstants(text){const vars=new Map();const re=/(?:const|let|var)\s+([A-Za-z_$][\w$]{0,80})\s*=\s*(["'`])([^"'`\n]{0,500})\2/g;let m;while((m=re.exec(text))&&vars.size<3500)vars.set(m[1],m[3]);return vars;}
function resolveExpr(expr,vars){const parts=String(expr).split(/\s*\+\s*/);if(parts.length>16)return null;let out='';for(const raw of parts){const p=raw.trim().replace(/^\((.*)\)$/,'$1');const q=p.match(/^(["'`])([\s\S]*?)\1$/);if(q){out+=q[2];continue;}if(vars.has(p)){out+=vars.get(p);continue;}return null;}return out;}
function foldVariableConcats(text){const vars=stringConstants(text);const re=/(?:const|let|var)\s+([A-Za-z_$][\w$]{0,80})\s*=\s*([^;\n]{1,1000})/g;let rounds=0,m;while(rounds++<5){let changed=false;re.lastIndex=0;while((m=re.exec(text))){if(vars.has(m[1]))continue;const v=resolveExpr(m[2],vars);if(v!=null&&v.length<=1200){vars.set(m[1],v);changed=true;}}if(!changed)break;}let synthetic='';for(const [k,v] of vars)synthetic+=`\n${k}="${v.replace(/"/g,'\\"')}";`;return text+synthetic;}
function normalize(text=''){return foldVariableConcats(foldLiteralConcats(decodeEscapes(text)));}
function first(text,patterns){for(const re of patterns){const m=text.match(re);if(m?.[1])return m[1];}return null;}

function objectAssignments(text){
  const vars=stringConstants(text), out=[];
  const patterns=[/(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*\{([\s\S]{1,2600}?)\}\s*[;,]/g,/initializeApp\s*\(\s*\{([\s\S]{1,2600}?)\}\s*\)/g,/firebase\.initializeApp\s*\(\s*\{([\s\S]{1,2600}?)\}\s*\)/g];
  let m;
  for(const re of patterns){while((m=re.exec(text))&&out.length<80){const body=m[2]||m[1];out.push({name:m[2]?m[1]:null,body});}}
  const refs=/initializeApp\s*\(\s*([A-Za-z_$][\w$]*)\s*\)|firebase\.initializeApp\s*\(\s*([A-Za-z_$][\w$]*)\s*\)/g;
  while((m=refs.exec(text))){const name=m[1]||m[2];const decl=new RegExp(`(?:const|let|var)\\s+${name.replace(/[$]/g,'\\$&')}\\s*=\\s*\\{([\\s\\S]{1,2600}?)\\}\\s*[;,]`);const d=text.match(decl);if(d)out.push({name,body:d[1]});}
  const readValue=(body,key)=>{const re=new RegExp(`(?:["']?${key}["']?)\\s*:\\s*([^,}\\n]+)`,'i');const hit=body.match(re);if(!hit)return null;const expr=hit[1].trim();const q=expr.match(/^(["'`])([^"'`]*)\1$/);if(q)return q[2];return resolveExpr(expr,vars)||vars.get(expr)||null;};
  return out.map(o=>({name:o.name,apiKey:readValue(o.body,'apiKey'),authDomain:readValue(o.body,'authDomain'),projectId:readValue(o.body,'projectId'),storageBucket:readValue(o.body,'storageBucket'),appId:readValue(o.body,'appId')}));
}

function firebaseApiKey(text){
  const explicit=first(text,[/[?&]key=([A-Za-z0-9_\-]{20,})/i,/\b(?:apiKey|firebaseApiKey|FIREBASE_API_KEY|NEXT_PUBLIC_FIREBASE_API_KEY|VITE_FIREBASE_API_KEY|REACT_APP_FIREBASE_API_KEY|NUXT_PUBLIC_FIREBASE_API_KEY|PUBLIC_FIREBASE_API_KEY)\b\s*[:=]\s*["'`]([A-Za-z0-9_\-]{20,})["'`]/i,/["'](?:apiKey|firebaseApiKey)["']\s*:\s*["']([A-Za-z0-9_\-]{20,})["']/i,/identitytoolkit\.googleapis\.com[^\n]{0,1600}?[?&]key=([A-Za-z0-9_\-]{20,})/i]);
  if(explicit)return explicit;
  const objs=objectAssignments(text);for(const o of objs)if(o.apiKey&&o.apiKey.length>=20)return o.apiKey;
  const keys=[...new Set(text.match(/AIza[0-9A-Za-z_\-]{30,}/g)||[])];if(keys.length===1)return keys[0];
  for(const key of keys){const i=text.indexOf(key),around=text.slice(Math.max(0,i-4000),Math.min(text.length,i+4000));if(/firebase|initializeApp|getAuth|firebaseapp\.com|identitytoolkit|securetoken|authDomain|projectId|signInWithEmailAndPassword/i.test(around))return key;}return null;
}
function mergeFirebase(base={},found={},source){return{apiKey:base.apiKey||found.apiKey||null,authDomain:base.authDomain||found.authDomain||null,projectId:base.projectId||found.projectId||null,passwordFlow:Boolean(base.passwordFlow||found.passwordFlow),source:(base.apiKey?base.source:null)||(found.apiKey?source||found.source:null)||base.source||found.source||'none'};}
function firebaseConfig(corpus){
  const text=normalize(corpus), objs=objectAssignments(text);let apiKey=firebaseApiKey(text),authDomain=null,projectId=null;
  for(const o of objs){apiKey=apiKey||o.apiKey;authDomain=authDomain||o.authDomain;projectId=projectId||o.projectId;}
  authDomain=authDomain||first(text,[/\b(?:authDomain|FIREBASE_AUTH_DOMAIN|NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN|VITE_FIREBASE_AUTH_DOMAIN|REACT_APP_FIREBASE_AUTH_DOMAIN|PUBLIC_FIREBASE_AUTH_DOMAIN)\b\s*[:=]\s*["'`]([^"'`\s]+)["'`]/i,/\b([a-z0-9-]+\.firebaseapp\.com)\b/i]);
  projectId=projectId||first(text,[/\b(?:projectId|FIREBASE_PROJECT_ID|NEXT_PUBLIC_FIREBASE_PROJECT_ID|VITE_FIREBASE_PROJECT_ID|REACT_APP_FIREBASE_PROJECT_ID|PUBLIC_FIREBASE_PROJECT_ID)\b\s*[:=]\s*["'`]([^"'`\s]+)["'`]/i,/https?:\/\/([a-z0-9-]+)\.firebaseio\.com/i,/https?:\/\/([a-z0-9-]+)\.firebasedatabase\.app/i]);
  if(!projectId&&authDomain?.endsWith('.firebaseapp.com'))projectId=authDomain.slice(0,-'.firebaseapp.com'.length);if(!authDomain&&projectId)authDomain=`${projectId}.firebaseapp.com`;
  const passwordFlow=/signInWithEmailAndPassword|accounts:signInWithPassword|EMAIL_PASSWORD_SIGN_IN|signInWithPassword|passwordSignIn/i.test(text);
  return{apiKey,authDomain,projectId,passwordFlow,source:apiKey?(objs.some(o=>o.apiKey===apiKey)?'semantic-config':'corpus'):'none'};
}

function supabaseConfig(corpus){const text=normalize(corpus);const url=first(text,[/\b(?:supabaseUrl|SUPABASE_URL|NEXT_PUBLIC_SUPABASE_URL|VITE_SUPABASE_URL|REACT_APP_SUPABASE_URL)\s*[:=]\s*["'`](https:\/\/[^"'`\s]+)["'`]/i,/(https:\/\/[a-z0-9-]+\.supabase\.co)/i]);const anonKey=first(text,[/\b(?:supabaseAnonKey|SUPABASE_ANON_KEY|NEXT_PUBLIC_SUPABASE_ANON_KEY|VITE_SUPABASE_ANON_KEY|REACT_APP_SUPABASE_ANON_KEY)\s*[:=]\s*["'`]([^"'`\s]{40,})["'`]/i,/\b(eyJ[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+)\b/]);return{url,anonKey,passwordFlow:/signInWithPassword|grant_type=password/i.test(text),source:(url||anonKey)?'corpus':'none'};}

async function readLimited(response,max=MAX_BYTES){const reader=response.body?.getReader();if(!reader)return'';const chunks=[];let total=0;while(true){const{done,value}=await reader.read();if(done)break;const left=max-total;if(left<=0)break;const part=value.byteLength>left?value.slice(0,left):value;chunks.push(part);total+=part.byteLength;if(value.byteLength>left)break;}try{await reader.cancel();}catch{}const out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength;}return new TextDecoder().decode(out);}
async function safeFetch(url,headers={}){let target;try{target=parseTarget(url);}catch{return null;}if(target.protocol!=='https:')return null;const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT);try{return await fetch(target.toString(),{redirect:'follow',signal:c.signal,headers:{'user-agent':'LIMPO-Auth-Engine/2.1',...headers}});}catch{return null;}finally{clearTimeout(t);}}
async function fetchPublicConfig(url,max=MAX_BYTES){const r=await safeFetch(url,{'accept':'application/json,text/javascript,text/plain,*/*;q=0.4'});if(!r?.ok)return null;return(await readLimited(r,max))||null;}
async function enrichFirebaseFromHost(initial,ctx){if(initial.apiKey)return initial;const hosts=[];try{hosts.push(new URL(ctx?.finalUrl||ctx?.requestedUrl).hostname);}catch{}if(initial.authDomain)hosts.push(initial.authDomain);if(initial.projectId)hosts.push(`${initial.projectId}.firebaseapp.com`);let current={...initial};for(const host of [...new Set(hosts)].slice(0,3))for(const path of ['/__/firebase/init.json','/__/firebase/init.js']){const text=await fetchPublicConfig(`https://${host}${path}`);if(!text)continue;current=mergeFirebase(current,firebaseConfig(text),'firebase-runtime-probe');if(current.apiKey)return current;}return current;}
async function bundleTotal(url){const r=await safeFetch(url,{'accept':'application/javascript,text/javascript,*/*;q=0.4','range':'bytes=0-0'});if(!r?.ok&&r?.status!==206)return 0;const cr=r.headers.get('content-range')||'';const total=Number((cr.match(/\/(\d+)$/)||[])[1]||r.headers.get('content-length')||0);try{await r.body?.cancel();}catch{}return total;}
async function fetchBundleRange(url,start,end){const r=await safeFetch(url,{'accept':'application/javascript,text/javascript,*/*;q=0.4','range':`bytes=${start}-${end}`});if(!r?.ok&&r?.status!==206)return'';return await readLimited(r,BUNDLE_SLICE);}
function orderedScripts(ctx){const scripts=[...new Set(ctx?.resources?.scripts||[])];const score=x=>(/auth|login|identity|account|firebase|config|runtime/i.test(x)?3:0)+(/main|app|index/i.test(x)?1:0);return scripts.sort((a,b)=>score(b)-score(a)).slice(0,14);}
async function enrichFirebaseFromBundles(initial,ctx){if(initial.apiKey)return initial;let spent=0,current={...initial};for(const url of orderedScripts(ctx)){const total=await bundleTotal(url);if(!total)continue;const starts=[];if(total<=2_200_000){for(let s=0;s<total;s+=BUNDLE_SLICE)starts.push(s);}else{const slots=10;for(let i=0;i<slots;i++)starts.push(Math.max(0,Math.floor((total-BUNDLE_SLICE)*(i/(slots-1)))));}for(const start of [...new Set(starts)]){if(spent>=BUNDLE_BUDGET)return current;const end=Math.min(total-1,start+BUNDLE_SLICE-1),text=await fetchBundleRange(url,start,end);spent+=Math.max(0,end-start+1);if(!text)continue;current=mergeFirebase(current,firebaseConfig(text),'targeted-bundle-scan');if(current.apiKey)return current;}}return current;}
function candidateMapUrls(ctx){const out=new Set(ctx?.resources?.sourceMaps||[]);for(const script of ctx?.resources?.scripts||[])try{const u=new URL(script);if(/\.m?js(?:$|\?)/i.test(u.pathname+u.search))out.add(script.replace(/(\.m?js)(\?.*)?$/i,'$1.map$2'));}catch{}return[...out].slice(0,MAX_MAPS);}
async function enrichFirebaseFromSourceMaps(initial,ctx){if(initial.apiKey)return initial;let current={...initial};for(const url of candidateMapUrls(ctx)){const text=await fetchPublicConfig(url,MAP_BYTES);if(!text)continue;let searchable=text;try{const map=JSON.parse(text);searchable=[...(map.sources||[]),...(map.sourcesContent||[])].join('\n');}catch{}current=mergeFirebase(current,firebaseConfig(searchable),'source-map');if(current.apiKey)return current;}return current;}
function configEndpointCandidates(ctx){const out=new Set(),corpus=normalize((ctx?.corpus||[]).join('\n'));const add=raw=>{try{const u=parseTarget(String(raw));if(u.protocol==='https:'&&!/login|signin|password|session|token/i.test(u.pathname))out.add(u.toString());}catch{}};for(const raw of ctx?.endpoints||[]){try{const u=new URL(raw);if(/(?:^|\/)(?:config|configuration|runtime|settings|environment|env|firebase|public-config|app-config)(?:[./?_-]|$)|\.json(?:\?|$)/i.test(u.pathname+u.search))add(u.toString());}catch{}}let m;const abs=/https:\/\/[^"'`\s<>]+/gi;while((m=abs.exec(corpus))&&out.size<60)if(/config|env|settings|runtime|firebase|\.json/i.test(m[0]))add(m[0]);try{const base=new URL(ctx?.finalUrl||ctx?.requestedUrl),rel=/["'`]([^"'`\s]{1,180}(?:config|env|settings|runtime|firebase)[^"'`\s]{0,120}(?:\.json|\.js)?(?:\?[^"'`]*)?)["'`]/gi;while((m=rel.exec(corpus))&&out.size<60)try{add(new URL(m[1],base).toString());}catch{}}catch{}return[...out].slice(0,MAX_CONFIG_ENDPOINTS);}
async function enrichFirebaseFromConfigEndpoints(initial,ctx){if(initial.apiKey)return initial;let current={...initial};for(const url of configEndpointCandidates(ctx)){const text=await fetchPublicConfig(url);if(!text)continue;current=mergeFirebase(current,firebaseConfig(text),'public-config-endpoint');if(current.apiKey)return current;}return current;}

export function extractRuntimeConfig(providerId,ctx){const corpus=(ctx?.corpus||[]).join('\n');if(providerId==='firebase')return{firebase:firebaseConfig(corpus)};if(providerId==='supabase')return{supabase:supabaseConfig(corpus)};return{};}
export async function reconstructRuntimeConfig(providerId,ctx){const runtime=extractRuntimeConfig(providerId,ctx);if(providerId==='firebase'&&runtime.firebase){runtime.firebase=await enrichFirebaseFromHost(runtime.firebase,ctx);runtime.firebase=await enrichFirebaseFromConfigEndpoints(runtime.firebase,ctx);runtime.firebase=await enrichFirebaseFromBundles(runtime.firebase,ctx);runtime.firebase=await enrichFirebaseFromSourceMaps(runtime.firebase,ctx);runtime.firebase=await enrichFirebaseFromHost(runtime.firebase,ctx);}return runtime;}
export function publicRuntimeSummary(runtime={}){const out={};if(runtime.firebase)out.firebase={apiKey:Boolean(runtime.firebase.apiKey),authDomain:Boolean(runtime.firebase.authDomain),projectId:Boolean(runtime.firebase.projectId),passwordFlow:Boolean(runtime.firebase.passwordFlow),source:runtime.firebase.source||'none'};if(runtime.supabase)out.supabase={url:Boolean(runtime.supabase.url),anonKey:Boolean(runtime.supabase.anonKey),passwordFlow:Boolean(runtime.supabase.passwordFlow),source:runtime.supabase.source||'none'};return out;}
